# PW 0: Intro to Python (Group 1)


## **Additional Python Concepts**

To complement the provided material, the following Python concepts are crucial for solving the exercises.

## 1. **String Methods**
- **Uppercase**: Convert a string to uppercase using `.upper()`.
  
  **Example**:
  ```python
  text = "hello world"
  print(text.upper())  # Output: HELLO WORLD
  ```

- **Lowercase**: Convert a string to lowercase using `.lower()`.
  
  **Example**:
  ```python
  text = "HELLO WORLD"
  print(text.lower())  # Output: HELLO WORLD
  ```

- **Splitting Strings**: Use `.split()` to divide a string into a list.
  
  **Example**:
  ```python
  sentence = "Hello,Computer,Science"
  words = sentence.split(",")  # Output: ['Hello', 'Computer', 'Science']
  ```

- **Joining Strings**: Use `.join()` to concatenate a list of strings into a single string with a specified separator.
  
  **Example**:
  ```python
  words = ['hello', 'world']
  sentence = ' '.join(words)  # Output: 'hello world'
  ```

## 2. **Input and Output**
- **`input()`**: This function allows the user to input data from the console. The input is always read as a string.
  
  **Example**:
  ```python
  user_input = input("Enter your name: ")
  print(f"Hello, {user_input}!")
  ```

- To handle multiple comma-separated values in one input, use the `split()` method.

  **Example**:
  ```python
  values = input("Enter numbers: ").split(',')
  print(values)
  ```

- **Print in the Same Line**: To print without moving to a new line after each print, use:
  ```python
  print("Hello World!", end=' ')
  ```

## 3. **Data Type Conversions**
- **Convert to Integer**: You can convert a string or a float to an integer using the `int()` function.
  
  **Example**:
  ```python
  num_str = "10"
  num_int = int(num_str)  # Converts "10" to 10
  ```

- **Convert to String**: You can convert an integer or a float to a string using the `str()` function.
  
  **Example**:
  ```python
  num = 123
  num_str = str(num)  # Converts 123 to "123"
  ```

- **Convert to List**: You can convert a string to a list of characters using `list()`.
  
  **Example**:
  ```python
  text = "hello"
  text_list = list(text)  # Converts "hello" to ['h', 'e', 'l', 'l', 'o']
  ```

- **Convert to Tuple**: You can convert a list or string to a tuple using `tuple()`.
  
  **Example**:
  ```python
  text = "hello"
  text_tuple = tuple(text)  # Converts "hello" to ('h', 'e', 'l', 'l', 'o')
  ```

## 🚨 Important Instructions 🚨
Please rename the file to include your first name and last name.
Example: `Group1_FirstName_LastName_tp1.ipynb`
No AI tools allowed! 🚫🤖

## Question 1

>***Write a generator function to iterate through numbers between 0 and n that are divisible by 5.***

In [1]:
def div_5(n:int):
    for x in range(0,n,5): print(5)
div_5(100)

5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5


## Question 2

>***Write a function that can receive two integers in string form, multiply them, and print the result.***

In [2]:
def two_strs(a:str,b:str): print(int(a)+int(b))

## Question 3

>***Write a function that accepts two strings as input and prints the string with the smallest length. If they have the same length, print both strings.***

In [3]:
def min_len(a:str,b:str):
    if len(a)<len(b): print(a)
    elif len(a)>len(b): print(b)
    else: print(a,b)

## Question 4

>***With a tuple `(1,2,3,4,5,6,7,8,9,10)`, write a program to print every second value in the tuple.Expected Output: `(2, 4, 6, 8, 10)`***

In [4]:
def sec_value(a:(int)): print(a[1::2])
sec_value((1,2,3,4,5,6,7,8,9,10))

(2, 4, 6, 8, 10)


## Question 5

>***Write a program to remove all odd numbers from `[3,6,9,12,15,18]`.***

In [5]:
def remove_odds(a:[int]): print([x for x in a if x%2==0])
remove_odds([1,2,3,4,5,6,7,8,9,10])

[2, 4, 6, 8, 10]


## Question 6

>***Write a program to find all numbers between 1500 and 2700 that are divisible by 7 but not multiples of 5. Print them as a comma-separated sequence.***

In [6]:
def div_by_7_not_5(): 
    for x in range(1500,2700) : 
        if x%7==0 and x%5!=0: 
            print(f"{x},",end="")   
    
div_by_7_not_5()

1512,1519,1526,1533,1547,1554,1561,1568,1582,1589,1596,1603,1617,1624,1631,1638,1652,1659,1666,1673,1687,1694,1701,1708,1722,1729,1736,1743,1757,1764,1771,1778,1792,1799,1806,1813,1827,1834,1841,1848,1862,1869,1876,1883,1897,1904,1911,1918,1932,1939,1946,1953,1967,1974,1981,1988,2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,

## Question 7

>***With a given integer  n , write a program to generate a dictionary that contains key-value pairs  (i, i*i) , where  i  is an integer between  1  and  n  **(both included)**. The program should then print the dictionary.***

Suppose the following input is supplied to the program:
`8`

The output should be:
`{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}`

**Hints**:  
Assume the input data is provided via the console. Use `input()` to read the string value and `int()` to convert it to an integer.


In [7]:
def fact_dict(n:int):
    d = {}
    for x in range(1,n+1): d[x]=x*x
    print(d)

fact_dict(5)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


## Question 8

>***Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
Suppose the following input is supplied to the program:
`"34,67,55,33,12,98"`***
Then, the output should be:
`['34', '67', '55', '33', '12', '98']`
`('34', '67', '55', '33', '12', '98')`

**Hints:**
Use `input()` to read sequence of comma-separated numbers. Use `list.split()` method to divide a string into a list. Use `tuple()` function can convert list to tuple.

In [8]:
def csv(a:str): print(a.split(","))

## Question 9

>***Write a program that takes a sequence of lines (read line by line) as input and outputs the same lines with all characters converted to uppercase.***

For example, if the following input is provided:

```
Hello world
Practice makes perfect
```

The output should be:
```
HELLO WORLD
PRACTICE MAKES PERFECT
```

In [9]:
def to_upper(a:str): print(a.upper())
for x in ["aflkj dslgkjsd", "fadkgjsdl"]: to_upper(x)

AFLKJ DSLGKJSD
FADKGJSDL


## Question 10

>***Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.***
>
Suppose the following input is supplied to the program:
```
hello world and practice makes perfect and hello world again
```
Then, the output should be:
```
again and hello makes perfect practice world
```
Hints:
                                                   
We use `set()`  to remove duplicated data automatically (by converting list to set) and then use sorted() to sort the data.

In [10]:
def remove_duplicates(a:str): print( " ".join( set(a.split(" ")) ) ) 

print(remove_duplicates("hello world and practice makes perfect and hello world again"))

makes and hello practice world perfect again
None


## Question 11

>***Define a function which can generate a dictionary where the keys are numbers between $1$ and $20$ (both included) and the values are square of keys. The function should just print the keys only.***

In [11]:
def square_dict_keys(n:int): 
    x = {x:x*x for x in range(1,n+1)}
    print(x.keys())
square_dict_keys(8)

dict_keys([1, 2, 3, 4, 5, 6, 7, 8])


## Question 12

>***Define a function that can generate a list where the values are the squares of numbers between 1 and 19 , with a step = 2 `[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]` . The function should then print the first 5 elements from the generated list.***

- the function should print the squares of numbers like `[1, 9, 25, 49, 81]`.


In [12]:
def sqr():
    x = [x**2 for x in range(1,19,2)]
    print(x[0:5])
    
sqr()

[1, 9, 25, 49, 81]


## Question 13


>***Write a program that generates all possible sentences where the subject is chosen from `["She", "They"]`, the verb is chosen from `["Watch", "Enjoy"]`, and the object is chosen from `["Movies", "Series"]`.***

In [13]:
def all_posible_com():
    a,b,c = ["She", "They"],["Watch", "Enjoy"],["Movies", "Series"]
    
    for x in a:
        for y in b:
            for z in c:
                print(f"{x} {y} {z}")

## Question 14

>***Write a program to count the number of occurrences of each word in a given sentence.***

In [14]:
def count_words(a:str):
    x = list(set(a.split(" ")))
    print( {x:a.count(x) for x in x} )
    

count_words("hello world and practice makes perfect and hello world again")
    

{'makes': 1, 'and': 2, 'hello': 2, 'practice': 1, 'world': 2, 'perfect': 1, 'again': 1}


## Question 15

>***Write a program to check if a number is a palindrome.***

In [15]:
def is_palindrome(a:int): print(str(a)==str(a)[::-1])

is_palindrome(121)

True


## Question 16

>***With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists.***

----------------------
**Hints:** Use built-in function set() and `intersection()` method to do set intersection operation.

**Example**:
```python
set1 = {1, 3, 6, 78, 35, 55}
set2 = {12, 24, 35, 24, 55, 88, 120, 155}

# Convert both lists to sets and find their intersection
intersection = set1.intersection(set2)

# Convert the resulting set back to a list
result = list(intersection)
print(intersection)  # Output: {35, 55}
```

In this example, the elements`35` and `55` are common to both lists, so it will be the only element in the intersection.

In [16]:

def intersection(a:[int],b:[int]):
    print( list(set(a).intersection(b)))
intersection([1,2,3,4,5,6,7,8,9,10],[1,3,5,7,9])


[1, 3, 5, 7, 9]


## Question 17

>***Write a program to generate a 3x3 matrix where each element is 0.***

In [17]:
def zeros_3_3():
    print( [[0 for x in range(3)] for y in range(3)] )

## Question 18

> ***Write a program that takes a 2D matrix as input and prints its transpose. The transpose of a matrix is obtained by swapping rows with columns.***

**Example**:
```
Input Matrix:
[
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]

Output Transpose:
[
  [1, 4, 7],
  [2, 5, 8],
  [3, 6, 9]
]
```

---

In [18]:
import numpy as np

def transpose_matrix(a:[[int]]):
    print(np.array(a).T)

transpose_matrix([[1,2,3],[4,5,6],[7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Question 19

>***Write a program to compute the following sum for a given integer `n` (n > 0):***
1/2 + 2/3 + 3/4 + ... + \ n/(n+1) 
### Example:
If the following `n` is given as input to the program:
```
5
```

Then, the output of the program should be:
```
3.55
```

In [19]:
def sum_1_n(n: int) -> float:
    if n < 1: return 0.0
    return sum(i / (i + 1) for i in range(1, n + 1))

print(sum_1_n(5))



3.55


## Question 20

> ***Write a program that multiplies two matrices. The program should take two matrices as input and output the resulting matrix after multiplication. Assume the matrices are compatible for multiplication.***

**Example**:
```
Matrix A:
[
  [1, 2],
  [3, 4],
  [5, 6]
]

Matrix B:
[
  [7, 8, 9],
  [10, 11, 12]
]

Output Matrix (A * B):
[
  [27, 30, 33],
  [61, 68, 75],
  [95, 106, 117]
]
```

---

In [20]:
import numpy as np

def matrix_mul(a:[[int]],b:[[int]]):
    print(np.matmul(np.array(a),np.array(b)))

matrix_mul([[1,2],[3,4],[5,6]],  [[7,8,9],[10,11,12]])

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


## Question 21

>***You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console.***
>***The sort criteria is:
1: Sort based on name;
2: Then sort based on age;
3: Then sort by score.
The priority is that name > age > score.***
If the following tuples are given as input to the program:

```
Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
```
Then, the output should be:
```
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]
```


In [22]:
import operator
def multi_sort(a):
    s = sorted(a, key = operator.itemgetter(0,1, 2))
    print(s)
    
multi_sort([ ('Tom', '19', '80'),('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('John', '20', '90'), ('Json', '21', '85')]   )

[('John', '20', '90'), ('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]


## Question 22


>***Write a binary search function `binary_search(arr, target)` which searches an item in a sorted list. The function should return the index of element to be searched in the list.***

In [23]:
def binary_search(arr,target):
    l,m,r = 0,len(arr)//2,len(arr)-1
    
    while l < r: 
        if arr[m] > target: l,m = m, (l+m)//2
        elif arr[m] < target: r,m = m, (l+m)//2
        else : return True
    
    return False

print( binary_search( [1,2,3,4,5,6] ,4) )
print( binary_search( [1,2,3,4,5,6] ,10) )
    

True
False


## Question 23

>***Write a program to print the elements of a matrix in a spiral order. The matrix should be traversed in a spiral starting from the top-left corner.***

**Example**:
```
Input Matrix:
[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]
]

Output (Spiral Order):
1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5, 6, 7, 11, 10
```

---

In [24]:
def spiral_order(arr:[[int]]):
    for x in range (len(arr)):
        for y in range(len(arr[0])):
            print(arr[x][y],end=", ")
            
spiral_order([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]
])

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 

## Question 24


>***You are given an integer, N. Your task is to print an alphabet rangoli of size N. (Rangoli is a form of Indian folk art based on creation of patterns.)***

>***Different sizes of alphabet rangoli are shown below:***
>```
>#size 3
>
>----c----
>--c-b-c--
>c-b-a-b-c
>--c-b-c--
>----c----
>
>#size 5
>
>--------e--------
>------e-d-e------
>----e-d-c-d-e----
>--e-d-c-b-c-d-e--
>e-d-c-b-a-b-c-d-e
>--e-d-c-b-c-d-e--
>----e-d-c-d-e----
>------e-d-e------
>--------e--------
>```
### Hints 
>***First print the half of the Rangoli in the given way and save each line in a list. Then print the list in reverse order to get the rest.***

In [25]:
import string

def print_rangoli(size):
    alpha = string.ascii_lowercase[:size]
    lines = []
    for i in range(size):
        s = '-'.join(alpha[size-1:i:-1] + alpha[i:size]) # this should return : c-b-a-b-c
        lines.append(s.center(4*size-3, '-'))            # this should return : --c-b-a-b-c--
    print('\n'.join(lines[::-1] + lines[1:]))

print_rangoli(2)
print_rangoli(5)

--b--
b-a-b
--b--
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------
